### ISSUE TITLE
进不去

### ISSUE THREAD

**Issue by xjh2009** [ndxzzy/webmc-server#3]
18:38:09 [严重] [/127.0.0.1:61679] <-> InitialHandler - encountered exception
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Unknown packet id 115
    at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:393)
    at io.netty.handler.codec.ByteToMessageDecoder.messageReceived(ByteToMessageDecoder.java:138)
    at io.netty.channel.DefaultChannelHandlerContext.invokeMessageReceived(DefaultChannelHandlerContext.java:379)
    at io.netty.channel.DefaultChannelHandlerContext.fireMessageReceived(DefaultChannelHandlerContext.java:364)
    at io.netty.handler.timeout.ReadTimeoutHandler.messageReceived(ReadTimeoutHandler.java:150)
    at io.netty.channel.DefaultChannelHandlerContext.invokeMessageReceived(DefaultChannelHandlerContext.java:379)
    at io.netty.channel.DefaultChannelHandlerContext.fireMessageReceived(DefaultChannelHandlerContext.java:364)
    at io.netty.channel.DefaultChannelPipeline.fireMessageReceived(DefaultChannelPipeline.java:786)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:120)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:489)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:464)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:358)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Unknown packet id 115
    at net.md_5.bungee.protocol.Vanilla.read(Vanilla.java:131)
    at net.md_5.bungee.netty.PacketDecoder.decode(PacketDecoder.java:21)
    at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:356)
    ... 13 more
>

**Comment by pig8086** [comment]
本整合包的服务端可能不是最新版的，另外你可能知道eaglercraft项目已经被原作者删除了...

**Comment by xjh2009** [comment]
但是，我用的是仓库那个bungee和web，eaglecraft有backup，我frok过了，用那个web和bungee也不行
